/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AktivasiRouteImport } from './routes/aktivasi'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PanduanRouteImport } from './routes/panduan'
import { Route as SistemRouteImport } from './routes/sistem'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TroubleshootingRouteImport } from './routes/troubleshooting'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AktivasiRoute = AktivasiRouteImport.update({
  id: '/aktivasi',
  path: '/aktivasi',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PanduanRoute = PanduanRouteImport.update({
  id: '/panduan',
  path: '/panduan',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemRoute = SistemRouteImport.update({
  id: '/sistem',
  path: '/sistem',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TroubleshootingRoute = TroubleshootingRouteImport.update({
  id: '/troubleshooting',
  path: '/troubleshooting',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aktivasi': typeof AktivasiRoute
  '/faq': typeof FaqRoute
  '/panduan': typeof PanduanRoute
  '/sistem': typeof SistemRoute
  '/status': typeof StatusRoute
  '/troubleshooting': typeof TroubleshootingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aktivasi': typeof AktivasiRoute
  '/faq': typeof FaqRoute
  '/panduan': typeof PanduanRoute
  '/sistem': typeof SistemRoute
  '/status': typeof StatusRoute
  '/troubleshooting': typeof TroubleshootingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aktivasi': typeof AktivasiRoute
  '/faq': typeof FaqRoute
  '/panduan': typeof PanduanRoute
  '/sistem': typeof SistemRoute
  '/status': typeof StatusRoute
  '/troubleshooting': typeof TroubleshootingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aktivasi'
    | '/faq'
    | '/panduan'
    | '/sistem'
    | '/status'
    | '/troubleshooting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aktivasi'
    | '/faq'
    | '/panduan'
    | '/sistem'
    | '/status'
    | '/troubleshooting'
  id:
    | '__root__'
    | '/'
    | '/aktivasi'
    | '/faq'
    | '/panduan'
    | '/sistem'
    | '/status'
    | '/troubleshooting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AktivasiRoute: typeof AktivasiRoute
  FaqRoute: typeof FaqRoute
  PanduanRoute: typeof PanduanRoute
  SistemRoute: typeof SistemRoute
  StatusRoute: typeof StatusRoute
  TroubleshootingRoute: typeof TroubleshootingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktivasi': {
      id: '/aktivasi'
      path: '/aktivasi'
      fullPath: '/aktivasi'
      preLoaderRoute: typeof AktivasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panduan': {
      id: '/panduan'
      path: '/panduan'
      fullPath: '/panduan'
      preLoaderRoute: typeof PanduanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistem': {
      id: '/sistem'
      path: '/sistem'
      fullPath: '/sistem'
      preLoaderRoute: typeof SistemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/troubleshooting': {
      id: '/troubleshooting'
      path: '/troubleshooting'
      fullPath: '/troubleshooting'
      preLoaderRoute: typeof TroubleshootingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AktivasiRoute: AktivasiRoute,
  FaqRoute: FaqRoute,
  PanduanRoute: PanduanRoute,
  SistemRoute: SistemRoute,
  StatusRoute: StatusRoute,
  TroubleshootingRoute: TroubleshootingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
